version: '3'

services:
  db:
    image: mysql:5.7.24
    restart: always
    environment:
      MYSQL_DATABASE: questionnaire
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./initdb.d/conf.d:/etc/mysql/conf.d
      - ./initdb.d/sqls:/docker-entrypoint-initdb.d
