version: '3'

services:
  db:
    image: mysql:5.7.24
    environment:
      MYSQL_DATABASE: questionnaire
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
